#!/bin/bash
# BUILD AND TEST YOUR LOGIN SYSTEM

echo "=========================================="
echo "  FURNITURE VISUALIZER - LOGIN SYSTEM"
echo "  Build & Test Instructions"
echo "=========================================="
echo ""

echo "STEP 1: Update dependencies"
echo "Command: mvn clean install"
echo "This will download BCrypt and compile all code"
echo ""

echo "STEP 2: Set up MongoDB (if not already done)"
echo "Option A - Docker:"
echo "  docker run -d -p 27017:27017 --name mongodb mongo:latest"
echo ""
echo "Option B - Windows Local:"
echo "  Download from: mongodb.com/try/download/community"
echo "  Run installer"
echo ""
echo "Option C - MongoDB Atlas:"
echo "  Sign up at: mongodb.com/cloud/atlas"
echo "  Create free cluster"
echo ""

echo "STEP 3: Verify MongoDB Connection"
echo "Command: mongosh"
echo "Expected: test>"
echo ""

echo "STEP 4: Run the application"
echo "Command: mvn exec:java@App"
echo "Or: Right-click App.java and select 'Run'"
echo ""

echo "STEP 5: Test Login & Registration"
echo "1. You should see a Login screen"
echo "2. Click 'Sign Up' to create a new account"
echo "3. Fill in: Email, Password, First Name, Last Name"
echo "   Password requirements:"
echo "   - At least 8 characters"
echo "   - Uppercase letter (A-Z)"
echo "   - Lowercase letter (a-z)"
echo "   - Number (0-9)"
echo "   - Special character (!@#$%^&*)"
echo "4. Click 'Create Account'"
echo "5. You should be taken back to Login"
echo "6. Login with your new credentials"
echo "7. You should see the main app!"
echo ""

echo "STEP 6: Test Data Persistence"
echo "1. Close the application"
echo "2. Run it again"
echo "3. Try to login with same credentials"
echo "4. You should be able to login!"
echo "5. Your account data is stored in MongoDB"
echo ""

echo "=========================================="
echo "  FILES CREATED/MODIFIED"
echo "=========================================="
echo ""

echo "EXCEPTION CLASSES (NEW):"
echo "  ✓ AuthenticationException.java"
echo "  ✓ RegistrationException.java"
echo "  ✓ InvalidCredentialsException.java"
echo ""

echo "DATA MODELS:"
echo "  ✓ User.java (IMPLEMENTED)"
echo "  ✓ Role.java (IMPLEMENTED)"
echo ""

echo "PERSISTENCE LAYER:"
echo "  ✓ UserStore.java (IMPLEMENTED - MongoDB CRUD)"
echo "  ✓ ValidationUtil.java (IMPLEMENTED)"
echo ""

echo "BUSINESS LOGIC:"
echo "  ✓ AuthService.java (IMPLEMENTED - Login/Register)"
echo "  ✓ Session.java (IMPLEMENTED - Session Management)"
echo ""

echo "UI COMPONENTS:"
echo "  ✓ LoginPanel.java (IMPLEMENTED - Login Form)"
echo "  ✓ RegistrationPanel.java (CREATED - Registration Form)"
echo "  ✓ LoginFrame.java (IMPLEMENTED - Main Login Window)"
echo ""

echo "INTEGRATION:"
echo "  ✓ App.java (MODIFIED - Check for logged-in user)"
echo "  ✓ Navigator.java (MODIFIED - Add user info & logout)"
echo "  ✓ pom.xml (MODIFIED - Added BCrypt dependency)"
echo ""

echo "=========================================="
echo "  QUICK TEST"
echo "=========================================="
echo ""
echo "mvn clean install"
echo "mvn exec:java@App"
echo ""
echo "1. Sign Up with:"
echo "   Email: test@example.com"
echo "   Password: TestPassword123!"
echo "   Name: Test User"
echo ""
echo "2. Login with same credentials"
echo ""
echo "3. Close app and restart"
echo ""
echo "4. Login again - account still exists!"
echo ""
echo "=========================================="
echo "  READY TO GO!"
echo "=========================================="

